language: python
python:
- '2.7'
- '3.3'
- pypy

before_install:
  - sudo apt-get install -y python-dev

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - flake8
